### ISSUE TITLE
DPCNN: weight sharing of convolution units

### ISSUE THREAD

**Issue by fcharras** [riejohnson/ConText#5]
Thank you very much for releasing the code.

I'm having a hard time reading https://github.com/riejohnson/ConText/blob/master/examples/dpcnn-functions.sh are the weight of the convolution units intended to be shared across the different layers ?

There's no hint about this in the paper so I think it should not be shared, but this random independent implementation: https://github.com/Cheneng/DPCNN/blob/master/model/DPCNN.py made it so (but I found a few other errors within this repo).

**Comment by riejohnson** [comment]
> are the weight of the convolution units intended to be shared across the different layers ?

No.   The weights are not shared by different convolution layers.

**Comment by fcharras** [comment]
Thank you for the quick response. That pytorch implementation comes above yours in search results, but it has many errors, it can be misleading (even more so with its readme that contains the image of your paper). Might be a plus to contact the author to fix it or link to the official repo.
